### ISSUE TITLE
Parse node_info.json from OpsCenter Diagnostics Report

### ISSUE THREAD

**Issue by ErickRamirezDS** [erickramirezDSE/cass_log_tools#3]
Implement a new script which makes the node_info.json data readable.

**Comment by markcurtis1970** [comment]
I used this very crude one liner as a start, but we could really do with prefixing with the node IP / name:

```
for line in $(cut -d : -f1 node_info.json | grep "\".*\"" | sed -e "s/^ *\"//" -e "s/\"//" | sort -u | grep -v "^[1-2]"); do grep $line node_info.json ;done
```

**Comment by markcurtis1970** [comment]
I used these very simple python commands to get some particular output as an example. I think in this case python might be quite simple?

```
import json
data = json.loads(open('node_info.json').read())
for node in data:
    print data[node]['node_ip'],'\t',data[node]['agent_jvm_version']
```

**Comment by markcurtis1970** [comment]
New script added in the following pull request: https://github.com/erickramirezDSE/cass_log_tools/pull/4
